version: 'version: 3.1'

x-common-variables: &common-variables
  REACT_APP_SERVER_PORT: 8000

services: 
  db:
    image: mysql:9.2
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./SQL/Files/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
    # healthcheck:
    #   test: mysql -u root -p=MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\ || exit 1

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080

  server:
    restart: always
    image: python-api-2
    volumes:
      - ./server:/server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - 8000:8000
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=ynov_ci
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - PORT=8000
    depends_on:
      - db
    command: uvicorn server:app --proxy-headers --host 0.0.0.0 --port 8000
  react:
    image: react
    build:
      context: .
      dockerfile: ./DockerfileReact
    ports:
      - 3000:3000
    environment:
      <<: *common-variables
    volumes:
      - .:/app
      - /app/node_modules
      - /app/server
    depends_on:
      - server
    command: npm start
