#Create MySQL Image for JSP Tutorial Application
FROM mysql:9.2
# Use Docker secrets or environment variables to set MYSQL_ROOT_PASSWORD at runtime
# ENV MYSQL_ROOT_PASSWORD='root'
# ENV MYSQL_ROOT_PASSWORD ynovpwd
# COPY ./SQL/Files /docker-entrypoint-initdb.d
# COPY ./SQL/Files/migration-v001.sql /docker-entrypoint-initdb.d
EXPOSE 3306