version: 'version: 3.1'

x-common-variables: &common-variables
  REACT_APP_SERVER_PORT: 8000

services: 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  server:
    restart: always
    image: python-api-2
    volumes:
      - ./server:/server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - 8000:8000
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PORT=${PORT}
    command: uvicorn server:app --proxy-headers --host 0.0.0.0 --port 8000
  react:
    image: react
    build:
      context: .
      dockerfile: ./DockerfileReact
    ports:
      - 3000:3000
    environment:
      <<: *common-variables
    volumes:
      - .:/app
      - /app/node_modules
      - /app/server
    depends_on:
      - server
    command: npm start
